export const types = {

    //global
    TOGGLE_LOADING: 'TOGGLE_LOADING',
    CHANGE_FOOTER_INDEX: 'CHANGE_FOOTER_INDEX',
    RENDER_AGAIN_STACK_NAV: 'RENDER_AGAIN_STACK_NAV',

    //auth
    LOGIN_SAGA: 'LOGIN_SAGA',
    UPDATE_USER_DATA: 'UPDATE_USER_DATA',
    GAMES_SELECT_TYPE: 'GAMES_SELECT_TYPE',
    UPDATE_SELECTED_GAME_USERNAME: 'UPDATE_SELECTED_GAME_USERNAME',
    INSERT_LIST_OF_GAMES: 'INSERT_LIST_OF_GAMES',

    //chat
    CHANGE_MESSAGES_MODAL_INDEX: 'CHANGE_MESSAGES_MODAL_INDEX',

    //team
    CHANGE_CREATE_TEAM_MODAL_INDEX: 'CHANGE_CREATE_TEAM_MODAL_INDEX',
    TEAM_LIST_DATA: 'TEAM_LIST_DATA',
    UPDATE_TEAM_LIST: 'UPDATE_TEAM_LIST',
    //users
    USERS_LIST_DATA: 'USERS_LIST_DATA',

    //logout
    DESTROY_SESSION: 'DESTROY_SESSION',
}